# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 给时间一点时间
subtitle:
description: '一名编程开发者的学习笔记 | 技术实战经验分享 | 生活观察手记 '
keywords: '"编程笔记","技术博客","学习心得","全栈开发","生活随笔","个人成长"'
author: baopeg
language: zh-CN
timezone: 'Asia/Shanghai'


# Extensions
# theme: next
theme: butterfly

# URL
## 必须设置为GitHub Pages地址
url: https://baopeg.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
  lang: zh-CN
pretty_urls:
  trailing_index: true
  trailing_html: true

# Deployment
deploy:
  type: git
  repo: git@github.com:baopeg/baopeg.github.io.git
  branch: gh-pages # 改为GitHub Pages默认分支

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''
  exclude_languages: ['mermaid']

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:




